In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
events_file = Path("../data/raw/events.csv")
events_file

WindowsPath('../data/raw/events.csv')

In [5]:
sample_df = pd.read_csv(events_file, nrows=50000)
sample_df.head()

C:\Users\mehdi\AppData\Local\Temp\ipykernel_60480\4096888154.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,32,36,38,44,45,51,69,70,71,72,73,74,75,76,78,79,80,82,84,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109) have mixed types. Specify dtype option on import or set low_memory=False.
  sample_df = pd.read_csv(events_file, nrows=50000)

,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,...,player_off_permanent,goalkeeper_success_in_play,shot_follows_dribble,goalkeeper_lost_out,half_start_late_video_start,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,goalkeeper_saved_to_post,goalkeeper_success_out,half_end_early_video_end
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
sample_df.shape

(50000, 120)

In [7]:
sample_df.columns.tolist()

['ball_receipt_outcome',
 'ball_recovery_recovery_failure',
 'carry_end_location',
 'clearance_aerial_won',
 'clearance_body_part',
 'clearance_head',
 'clearance_left_foot',
 'clearance_right_foot',
 'counterpress',
 'dribble_nutmeg',
 'dribble_outcome',
 'dribble_overrun',
 'duel_outcome',
 'duel_type',
 'duration',
 'foul_committed_advantage',
 'foul_committed_card',
 'foul_committed_offensive',
 'foul_committed_penalty',
 'foul_committed_type',
 'foul_won_advantage',
 'foul_won_defensive',
 'foul_won_penalty',
 'goalkeeper_body_part',
 'goalkeeper_end_location',
 'goalkeeper_outcome',
 'goalkeeper_position',
 'goalkeeper_punched_out',
 'goalkeeper_technique',
 'goalkeeper_type',
 'id',
 'index',
 'interception_outcome',
 'location',
 'match_id',
 'minute',
 'miscontrol_aerial_won',
 'off_camera',
 'out',
 'pass_aerial_won',
 'pass_angle',
 'pass_assisted_shot_id',
 'pass_body_part',
 'pass_cross',
 'pass_cut_back',
 'pass_deflected',
 'pass_end_location',
 'pass_height',
 'pass_inswinging',
 'pass_length',
 'pass_outcome',
 'pass_outswinging',
 'pass_recipient',
 'pass_recipient_id',
 'pass_shot_assist',
 'pass_switch',
 'pass_technique',
 'pass_through_ball',
 'pass_type',
 'period',
 'play_pattern',
 'player',
 'player_id',
 'position',
 'possession',
 'possession_team',
 'possession_team_id',
 'related_events',
 'second',
 'shot_aerial_won',
 'shot_body_part',
 'shot_end_location',
 'shot_first_time',
 'shot_freeze_frame',
 'shot_key_pass_id',
 'shot_one_on_one',
 'shot_outcome',
 'shot_statsbomb_xg',
 'shot_technique',
 'shot_type',
 'substitution_outcome',
 'substitution_outcome_id',
 'substitution_replacement',
 'substitution_replacement_id',
 'tactics',
 'team',
 'team_id',
 'timestamp',
 'type',
 'under_pressure',
 '50_50',
 'bad_behaviour_card',
 'ball_recovery_offensive',
 'block_offensive',
 'goalkeeper_shot_saved_off_target',
 'shot_open_goal',
 'shot_saved_off_target',
 'goalkeeper_shot_saved_to_post',
 'injury_stoppage_in_chain',
 'pass_goal_assist',
 'pass_straight',
 'pass_no_touch',
 'clearance_other',
 'pass_miscommunication',
 'shot_saved_to_post',
 'block_deflection',
 'dribble_no_touch',
 'shot_redirect',
 'block_save_block',
 'shot_deflected',
 'player_off_permanent',
 'goalkeeper_success_in_play',
 'shot_follows_dribble',
 'goalkeeper_lost_out',
 'half_start_late_video_start',
 'goalkeeper_lost_in_play',
 'goalkeeper_penalty_saved_to_post',
 'goalkeeper_saved_to_post',
 'goalkeeper_success_out',
 'half_end_early_video_end']

In [8]:
pd.DataFrame({
    "column": sample_df.columns,
    "dtype": sample_df.dtypes.values,
    "non_null_count": sample_df.notna().sum().values,
    "null_count": sample_df.isna().sum().values,
    "null_pct": (sample_df.isna().mean().values * 100).round(2)
}).sort_values("null_pct", ascending=True)

,column,dtype,non_null_count,null_count,null_pct
30,id,object,50000,0,0.0
31,index,int64,50000,0,0.0
34,match_id,int64,50000,0,0.0
35,minute,int64,50000,0,0.0
60,play_pattern,object,50000,0,0.0
...,...,...,...,...,...
115,goalkeeper_lost_in_play,float64,0,50000,100.0
116,goalkeeper_penalty_saved_to_post,float64,0,50000,100.0
117,goalkeeper_saved_to_post,float64,0,50000,100.0
118,goalkeeper_success_out,float64,0,50000,100.0
119,half_end_early_video_end,float64,0,50000,100.0

In [9]:
sample_df["type"].value_counts(dropna=False)

type
Pass                 14402
Ball Receipt*        12977
Carry                 9920
Pressure              4617
Ball Recovery         1510
Duel                  1293
Clearance              905
Block                  549
Dribble                475
Interception           468
Goal Keeper            419
Miscontrol             415
Dispossessed           409
Shot                   344
Foul Committed         325
Dribbled Past          306
Foul Won               305
Substitution            76
Half Start              60
Half End                56
Injury Stoppage         32
Starting XI             30
Tactical Shift          29
50/50                   26
Shield                  19
Referee Ball-Drop       16
Bad Behaviour            6
Error                    4
Offside                  3
Own Goal Against         1
Own Goal For             1
Player Off               1
Player On                1
Name: count, dtype: int64

In [10]:
(
    sample_df["type"]
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

type
Pass                 28.80
Ball Receipt*        25.95
Carry                19.84
Pressure              9.23
Ball Recovery         3.02
Duel                  2.59
Clearance             1.81
Block                 1.10
Dribble               0.95
Interception          0.94
Goal Keeper           0.84
Miscontrol            0.83
Dispossessed          0.82
Shot                  0.69
Foul Committed        0.65
Dribbled Past         0.61
Foul Won              0.61
Substitution          0.15
Half Start            0.12
Half End              0.11
Injury Stoppage       0.06
Starting XI           0.06
Tactical Shift        0.06
50/50                 0.05
Shield                0.04
Referee Ball-Drop     0.03
Bad Behaviour         0.01
Error                 0.01
Offside               0.01
Own Goal Against      0.00
Own Goal For          0.00
Player Off            0.00
Player On             0.00
Name: proportion, dtype: float64

In [11]:
key_columns = [
    "match_id",
    "id",
    "index",
    "period",
    "timestamp",
    "minute",
    "second",
    "type",
    "possession",
    "possession_team",
    "play_pattern",
    "team",
    "player",
    "position",
    "location",
    "duration"
]

sample_df[key_columns].head(10)

,match_id,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,team,player,position,location,duration
0,3754058,9153e9f4-f69c-4e04-8f64-505592e212cd,1,1,00:00:00.000,0,0,Starting XI,1,Leicester City,Regular Play,Leicester City,NaN,NaN,NaN,0.000000
1,3754058,3fbcf4e7-94d1-485a-be85-fd26a6af0318,2,1,00:00:00.000,0,0,Starting XI,1,Leicester City,Regular Play,AFC Bournemouth,NaN,NaN,NaN,0.000000
2,3754058,06a9a4dc-d9c9-40f6-bd89-437ba7fe682d,3,1,00:00:00.000,0,0,Half Start,1,Leicester City,Regular Play,AFC Bournemouth,NaN,NaN,NaN,0.000000
3,3754058,100362ee-9311-4187-bd8a-0201d9db2565,4,1,00:00:00.000,0,0,Half Start,1,Leicester City,Regular Play,Leicester City,NaN,NaN,NaN,0.000000
4,3754058,3a645ce0-af88-4dfc-8f97-82d3770bc4ae,1927,2,00:00:00.000,45,0,Half Start,82,AFC Bournemouth,From Free Kick,AFC Bournemouth,NaN,NaN,NaN,0.000000
5,3754058,a8059850-8edc-4273-a102-1f6ad3ae782d,1928,2,00:00:00.000,45,0,Half Start,82,AFC Bournemouth,From Free Kick,Leicester City,NaN,NaN,NaN,0.000000
6,3754058,2ca23eea-a984-47e4-8243-8f00880ad1c9,5,1,00:00:01.753,0,1,Pass,2,AFC Bournemouth,From Kick Off,AFC Bournemouth,Dan Gosling,Right Center Midfield,"[61.0, 40.1]",0.308263
7,3754058,0fee7719-7e69-49c5-be81-3f2b77da604e,8,1,00:00:02.077,0,2,Pass,2,AFC Bournemouth,From Kick Off,AFC Bournemouth,Joshua King,Center Forward,"[60.4, 43.6]",0.933203
8,3754058,6362aa69-892f-4d11-8644-21a680ea7c66,10,1,00:00:03.010,0,3,Pass,2,AFC Bournemouth,From Kick Off,AFC Bournemouth,Andrew Surman,Center Defensive Midfield,"[48.0, 41.7]",2.454046
9,3754058,56da36e4-8b0d-4596-ba46-1d944c3d3f04,13,1,00:00:06.145,0,6,Pass,2,AFC Bournemouth,From Kick Off,AFC Bournemouth,Adam Smith,Right Back,"[37.5, 74.6]",1.795575

In [12]:
sample_df["match_id"].nunique()

15

In [13]:
print("Nombre de joueurs :", sample_df["player"].nunique())
print("Nombre d'équipes :", sample_df["team"].nunique())

Nombre de joueurs : 265
Nombre d'équipes : 15

In [14]:
passes_df = sample_df[sample_df["type"] == "Pass"].copy()
passes_df.head()

,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,...,player_off_permanent,goalkeeper_success_in_play,shot_follows_dribble,goalkeeper_lost_out,half_start_late_video_start,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,goalkeeper_saved_to_post,goalkeeper_success_out,half_end_early_video_end
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
pd.DataFrame({
    "column": passes_df.columns,
    "non_null_count": passes_df.notna().sum().values,
    "null_pct": (passes_df.isna().mean().values * 100).round(2)
}).sort_values("null_pct")

                               column  non_null_count  null_pct
14                           duration           14402       0.0
31                              index           14402       0.0
30                                 id           14402       0.0
47                        pass_height           14402       0.0
60                       play_pattern           14402       0.0
..                                ...             ...       ...
115           goalkeeper_lost_in_play               0     100.0
116  goalkeeper_penalty_saved_to_post               0     100.0
117          goalkeeper_saved_to_post               0     100.0
118            goalkeeper_success_out               0     100.0
119          half_end_early_video_end               0     100.0

[120 rows x 3 columns]

In [16]:
pass_columns_to_view = [
    "match_id",
    "team",
    "player",
    "minute",
    "second",
    "location",
    "pass_end_location",
    "pass_length",
    "pass_angle",
    "pass_height",
    "pass_outcome",
    "pass_type",
    "pass_body_part",
    "pass_cross",
    "pass_switch",
    "pass_shot_assist",
    "under_pressure"
]

available_pass_columns = [col for col in pass_columns_to_view if col in passes_df.columns]
passes_df[available_pass_columns].head(10)

,match_id,team,player,minute,second,location,pass_end_location,pass_length,pass_angle,pass_height,pass_outcome,pass_type,pass_body_part,pass_cross,pass_switch,pass_shot_assist,under_pressure
6,3754058,AFC Bournemouth,Dan Gosling,0,1,"[61.0, 40.1]","[60.4, 43.6]",3.551056,1.740575,Ground Pass,NaN,Kick Off,Right Foot,NaN,NaN,NaN,NaN
7,3754058,AFC Bournemouth,Joshua King,0,2,"[60.4, 43.6]","[48.0, 41.7]",12.544720,-2.989549,Ground Pass,NaN,NaN,Right Foot,NaN,NaN,NaN,NaN
8,3754058,AFC Bournemouth,Andrew Surman,0,3,"[48.0, 41.7]","[37.5, 76.1]",35.966790,1.867047,Ground Pass,NaN,NaN,Left Foot,NaN,NaN,NaN,NaN
9,3754058,AFC Bournemouth,Adam Smith,0,6,"[37.5, 74.6]","[27.4, 58.1]",19.345800,-2.120081,Ground Pass,NaN,NaN,Right Foot,NaN,NaN,NaN,NaN
10,3754058,AFC Bournemouth,Simon Francis,0,9,"[27.4, 63.9]","[35.1, 77.8]",15.890248,1.064920,Ground Pass,NaN,NaN,Right Foot,NaN,NaN,NaN,NaN
11,3754058,AFC Bournemouth,Adam Smith,0,12,"[30.4, 78.0]","[16.7, 75.5]",13.926234,-2.961097,Ground Pass,NaN,NaN,Left Foot,NaN,NaN,NaN,NaN
12,3754058,AFC Bournemouth,Simon Francis,0,15,"[19.1, 69.7]","[20.1, 29.3]",40.412373,-1.546049,Ground Pass,NaN,NaN,Right Foot,NaN,True,NaN,NaN
13,3754058,AFC Bournemouth,Steve Cook,0,18,"[26.4, 25.8]","[41.8, 4.7]",26.122213,-0.940311,Ground Pass,NaN,NaN,Right Foot,NaN,NaN,NaN,NaN
14,3754058,AFC Bournemouth,Charlie Daniels,0,22,"[38.1, 12.1]","[22.5, 16.4]",16.181780,2.872631,Ground Pass,NaN,NaN,Left Foot,NaN,NaN,NaN,NaN
15,3754058,AFC Bournemouth,Steve Cook,0,25,"[23.4, 27.8]","[20.4, 52.4]",24.782251,1.692148,Ground Pass,NaN,NaN,Right Foot,NaN,NaN,NaN,NaN

In [17]:
shots_df = sample_df[sample_df["type"] == "Shot"].copy()
shots_df.head()

,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,...,player_off_permanent,goalkeeper_success_in_play,shot_follows_dribble,goalkeeper_lost_out,half_start_late_video_start,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,goalkeeper_saved_to_post,goalkeeper_success_out,half_end_early_video_end
3149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
shot_columns_to_view = [
    "match_id",
    "team",
    "player",
    "minute",
    "second",
    "location",
    "shot_end_location",
    "shot_statsbomb_xg",
    "shot_outcome",
    "shot_body_part",
    "shot_type",
    "shot_first_time",
    "shot_one_on_one",
    "shot_open_goal",
    "under_pressure"
]

available_shot_columns = [col for col in shot_columns_to_view if col in shots_df.columns]
shots_df[available_shot_columns].head(10)

,match_id,team,player,minute,second,location,shot_end_location,shot_statsbomb_xg,shot_outcome,shot_body_part,shot_type,shot_first_time,shot_one_on_one,shot_open_goal,under_pressure
3149,3754058,AFC Bournemouth,Junior Stanislas,1,33,"[107.1, 26.6]","[109.7, 30.1]",0.020838,Blocked,Right Foot,Open Play,NaN,NaN,NaN,NaN
3150,3754058,AFC Bournemouth,Joshua King,4,23,"[113.7, 54.0]","[114.5, 52.6]",0.034462,Blocked,Right Foot,Open Play,NaN,NaN,NaN,NaN
3151,3754058,Leicester City,Riyad Mahrez,9,20,"[115.7, 50.5]","[120.0, 43.3, 3.6]",0.035481,Off T,Left Foot,Open Play,True,NaN,NaN,True
3152,3754058,AFC Bournemouth,Joshua King,13,11,"[113.9, 38.6]","[120.0, 46.0, 1.2]",0.383711,Off T,Head,Open Play,NaN,NaN,NaN,NaN
3153,3754058,Leicester City,José Leonardo Ulloa,25,47,"[96.7, 47.2]","[103.9, 40.1]",0.036740,Wayward,Right Foot,Open Play,NaN,NaN,NaN,NaN
3154,3754058,Leicester City,Jamie Vardy,25,49,"[111.3, 38.7]","[120.0, 36.0, 1.3]",0.575428,Post,Right Foot,Open Play,NaN,True,NaN,NaN
3155,3754058,AFC Bournemouth,Junior Stanislas,32,14,"[112.6, 28.7]","[120.0, 48.0, 5.3]",0.095998,Off T,Right Foot,Open Play,NaN,NaN,NaN,NaN
3156,3754058,Leicester City,José Leonardo Ulloa,33,52,"[112.1, 32.8]","[120.0, 48.3, 1.0]",0.047259,Off T,Head,Open Play,NaN,NaN,NaN,True
3157,3754058,AFC Bournemouth,Dan Gosling,36,57,"[108.4, 43.0]","[120.0, 41.4, 4.9]",0.256448,Off T,Right Foot,Open Play,True,NaN,NaN,NaN
3158,3754058,Leicester City,Jamie Vardy,37,43,"[114.2, 27.2]","[119.2, 50.5]",0.111973,Wayward,Left Foot,Open Play,NaN,True,NaN,NaN

In [19]:
carries_df = sample_df[sample_df["type"] == "Carry"].copy()
carries_df.head()

,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,...,player_off_permanent,goalkeeper_success_in_play,shot_follows_dribble,goalkeeper_lost_out,half_start_late_video_start,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,goalkeeper_saved_to_post,goalkeeper_success_out,half_end_early_video_end
1932,NaN,NaN,"[60.4, 43.6]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1933,NaN,NaN,"[37.5, 74.6]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1934,NaN,NaN,"[27.4, 63.9]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1935,NaN,NaN,"[30.4, 78.0]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1936,NaN,NaN,"[19.1, 69.7]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
carry_columns_to_view = [
    "match_id",
    "team",
    "player",
    "minute",
    "second",
    "location",
    "carry_end_location",
    "under_pressure"
]

available_carry_columns = [col for col in carry_columns_to_view if col in carries_df.columns]
carries_df[available_carry_columns].head(10)

,match_id,team,player,minute,second,location,carry_end_location,under_pressure
1932,3754058,AFC Bournemouth,Joshua King,0,2,"[60.4, 43.6]","[60.4, 43.6]",NaN
1933,3754058,AFC Bournemouth,Adam Smith,0,5,"[37.5, 76.1]","[37.5, 74.6]",NaN
1934,3754058,AFC Bournemouth,Simon Francis,0,7,"[27.4, 58.1]","[27.4, 63.9]",NaN
1935,3754058,AFC Bournemouth,Adam Smith,0,10,"[35.1, 77.8]","[30.4, 78.0]",True
1936,3754058,AFC Bournemouth,Simon Francis,0,13,"[16.7, 75.5]","[19.1, 69.7]",NaN
1937,3754058,AFC Bournemouth,Steve Cook,0,17,"[20.1, 29.3]","[26.4, 25.8]",NaN
1938,3754058,AFC Bournemouth,Charlie Daniels,0,20,"[41.8, 4.7]","[38.1, 12.1]",True
1939,3754058,AFC Bournemouth,Steve Cook,0,24,"[22.5, 16.4]","[23.4, 27.8]",NaN
1940,3754058,AFC Bournemouth,Simon Francis,0,27,"[20.4, 52.4]","[36.0, 67.8]",NaN
1941,3754058,AFC Bournemouth,Dan Gosling,0,32,"[51.2, 61.3]","[49.5, 59.0]",NaN

In [21]:
interceptions_df = sample_df[sample_df["type"] == "Interception"].copy()
interceptions_df.head()

,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,...,player_off_permanent,goalkeeper_success_in_play,shot_follows_dribble,goalkeeper_lost_out,half_start_late_video_start,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,goalkeeper_saved_to_post,goalkeeper_success_out,half_end_early_video_end
3498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
recoveries_df = sample_df[sample_df["type"] == "Ball Recovery"].copy()
recoveries_df.head()

,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,...,player_off_permanent,goalkeeper_success_in_play,shot_follows_dribble,goalkeeper_lost_out,half_start_late_video_start,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,goalkeeper_saved_to_post,goalkeeper_success_out,half_end_early_video_end
3253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
duels_df = sample_df[sample_df["type"] == "Duel"].copy()
duels_df.head()

,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,...,player_off_permanent,goalkeeper_success_in_play,shot_follows_dribble,goalkeeper_lost_out,half_start_late_video_start,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,goalkeeper_saved_to_post,goalkeeper_success_out,half_end_early_video_end
3066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
sample_df["location"].dropna().head(10)

6     [61.0, 40.1]
7     [60.4, 43.6]
8     [48.0, 41.7]
9     [37.5, 74.6]
10    [27.4, 63.9]
11    [30.4, 78.0]
12    [19.1, 69.7]
13    [26.4, 25.8]
14    [38.1, 12.1]
15    [23.4, 27.8]
Name: location, dtype: object

In [25]:
sample_df["location"].dropna().iloc[0], type(sample_df["location"].dropna().iloc[0])

('[61.0, 40.1]', str)

In [26]:
important_columns = [
    "match_id",
    "id",
    "index",
    "period",
    "timestamp",
    "minute",
    "second",
    "type",
    "possession",
    "possession_team",
    "play_pattern",
    "team",
    "player",
    "position",
    "location",
    "duration",
    "under_pressure",
    "counterpress",
    "pass_length",
    "pass_angle",
    "pass_height",
    "pass_end_location",
    "pass_outcome",
    "pass_type",
    "pass_body_part",
    "pass_cross",
    "pass_switch",
    "pass_shot_assist",
    "shot_end_location",
    "shot_statsbomb_xg",
    "shot_outcome",
    "shot_body_part",
    "shot_type",
    "carry_end_location",
    "dribble_outcome",
    "duel_type",
    "interception_outcome",
    "ball_recovery_recovery_failure"
]

[col for col in important_columns if col in sample_df.columns]

['match_id',
 'id',
 'index',
 'period',
 'timestamp',
 'minute',
 'second',
 'type',
 'possession',
 'possession_team',
 'play_pattern',
 'team',
 'player',
 'position',
 'location',
 'duration',
 'under_pressure',
 'counterpress',
 'pass_length',
 'pass_angle',
 'pass_height',
 'pass_end_location',
 'pass_outcome',
 'pass_type',
 'pass_body_part',
 'pass_cross',
 'pass_switch',
 'pass_shot_assist',
 'shot_end_location',
 'shot_statsbomb_xg',
 'shot_outcome',
 'shot_body_part',
 'shot_type',
 'carry_end_location',
 'dribble_outcome',
 'duel_type',
 'interception_outcome',
 'ball_recovery_recovery_failure']

## Premières conclusions de l’audit events

- La table events est une table large et hétérogène.
- La colonne `type` est centrale pour segmenter les actions.
- Les colonnes spécifiques (`pass_*`, `shot_*`, `carry_*`, etc.) ne sont remplies que pour certains types d’événements.
- Les coordonnées terrain (`location`, `pass_end_location`, `carry_end_location`, `shot_end_location`) seront clés pour le feature engineering.
- Les types d’événements prioritaires pour la V1 seront probablement :
  - Pass
  - Shot
  - Carry
  - Interception
  - Ball Recovery
  - Duel
- Un travail de parsing et de sélection de colonnes sera nécessaire avant de construire les features.

In [4]:
import pandas as pd
import ast

df = pd.read_csv("data/raw/lineups.csv")

sample_positions = df.loc[0, "positions"]
print(sample_positions)
print(type(sample_positions))

parsed = ast.literal_eval(sample_positions)
print(type(parsed))
print(parsed[:2])

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/lineups.csv'